apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: clouddns-dns01-solver-svc-acct
spec:
  backendType: azureKeyVault
  keyVaultName: dc6-general-20210701
  data:
    - key: clouddns-dns01-solver-svc-acct
      name: key.json
