traefik:
  resources:
     requests:
       cpu: "100m"
       memory: "50Mi"
     limits:
       cpu: "300m"
       memory: "150Mi"
  service:
    annotations:
      "service.beta.kubernetes.io/azure-load-balancer-resource-group": "dc6-resources"
    spec:
      loadBalancerIP: "104.40.140.153"  # Azure LP IP