- op: add
  path: /spec/template/spec/containers/0/args/-
  value:
    --auth-mode=sso

- op: add
  path: /spec/template/spec/containers/0/args/-
  value:
    --insecure

- op: add
  path: /spec/template/spec/containers/0/env
  value:
    - name: BASE_HREF
      value: "/argo/"

- op: replace
  path: /spec/template/spec/containers/0/readinessProbe/httpGet/scheme
  value: HTTP
