apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: argo-azureadapp-client-secret
spec:
  backendType: azureKeyVault
  keyVaultName: dc6-general-20210701
  data:
    - key: client-secret-key
      name: client-secret-secret
